/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FilterJDialog.java
 *
 * Created on 14.03.2010, 00:48:26
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.xml.ws.Action;

import message.MessageHandler;
import message.MessageType;

import org.jdom.Attribute;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.JDOMException;
import org.jdom.input.SAXBuilder;
import org.jdom.xpath.XPath;

import collector.data.Filter;
import collector.message.MessageCollector;
import core.config.Config;

/**
 * 
 * @author sucker
 */
public class FilterForm extends javax.swing.JDialog {

	/**
	 * Auto generated
	 */
	private static final long serialVersionUID = -6243931159056414082L;

	/** Creates new form FilterJDialog */
	public FilterForm(java.awt.Frame parent) {
		this(parent, null);
	}

	/** Creates new form FilterJDialog */
	public FilterForm(java.awt.Frame parent, Filter f) {
		super(parent);
		this.edit = f;
		initData();
		initComponents();
		setData();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		String language = Config.getConfig().getLanguage();

		Locale currLocale = new Locale(language);
		ResourceBundle filterFormBundle = ResourceBundle.getBundle(
				"gui/bundle/gui", currLocale);

		this.setTitle("CarCrawler - Filter form");
		setLocationRelativeTo(getOwner());

		noMakeMsg = filterFormBundle.getString("message.nomake");

		jPanel1 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jTextFieldVariante = new javax.swing.JTextField();
		jComboBoxModel = new javax.swing.JComboBox();
		jComboBoxMarke = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jComboBoxGear = new javax.swing.JComboBox();
		jComboBoxFuel = new javax.swing.JComboBox();
		jLabel11 = new javax.swing.JLabel();
		jComboBoxBody = new javax.swing.JComboBox();
		jLabel12 = new javax.swing.JLabel();
		jComboBoxENorm = new javax.swing.JComboBox();
		jLabel13 = new javax.swing.JLabel();
		jComboBoxRadius = new javax.swing.JComboBox();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jTextFieldPLZ = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jComboBoxPriceFrom = new javax.swing.JComboBox();
		jComboBoxPriceTo = new javax.swing.JComboBox();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel2 = new javax.swing.JLabel();
		jComboBoxMileageFrom = new javax.swing.JComboBox();
		jComboBoxMileageTo = new javax.swing.JComboBox();
		jLabel3 = new javax.swing.JLabel();
		jComboBoxPowerFrom = new javax.swing.JComboBox();
		jComboBoxPowerTo = new javax.swing.JComboBox();
		jLabel7 = new javax.swing.JLabel();
		jComboBoxYearFrom = new javax.swing.JComboBox();
		jComboBoxYearTo = new javax.swing.JComboBox();
		jSeparator2 = new javax.swing.JSeparator();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jSeparator3 = new javax.swing.JSeparator();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jCheckBoxABS = new javax.swing.JCheckBox();
		jCheckBoxAirbag = new javax.swing.JCheckBox();
		jCheckBoxAllrad = new javax.swing.JCheckBox();
		jCheckBoxESP = new javax.swing.JCheckBox();
		jCheckBoxAlarm = new javax.swing.JCheckBox();
		jCheckBoxWFSperre = new javax.swing.JCheckBox();
		jCheckBoxLock = new javax.swing.JCheckBox();
		jCheckBoxSAirbag = new javax.swing.JCheckBox();
		jCheckBoxNebel = new javax.swing.JCheckBox();
		jCheckBoxServo = new javax.swing.JCheckBox();
		jCheckBoxTraktion = new javax.swing.JCheckBox();
		jPanel3 = new javax.swing.JPanel();
		jCheckBoxAlufelgen = new javax.swing.JCheckBox();
		jCheckBoxAKupplung = new javax.swing.JCheckBox();
		jCheckBoxBordcomputer = new javax.swing.JCheckBox();
		jCheckBoxDachtraeger = new javax.swing.JCheckBox();
		jCheckBoxEinpark = new javax.swing.JCheckBox();
		jCheckBoxESitze = new javax.swing.JCheckBox();
		jCheckBoxFensterheber = new javax.swing.JCheckBox();
		jCheckBoxKlima = new javax.swing.JCheckBox();
		jCheckBoxLeder = new javax.swing.JCheckBox();
		jCheckBoxNavi = new javax.swing.JCheckBox();
		jCheckBoxRadioCD = new javax.swing.JCheckBox();
		jCheckBoxSchiebedach = new javax.swing.JCheckBox();
		jCheckBoxStandheizung = new javax.swing.JCheckBox();
		jCheckBoxSitzheizung = new javax.swing.JCheckBox();
		jCheckBoxTempomat = new javax.swing.JCheckBox();
		jCheckBoxTuning = new javax.swing.JCheckBox();
		jCheckBoxXenon = new javax.swing.JCheckBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel1.setName("jPanel1"); // NOI18N

		jLabel4.setText(filterFormBundle.getString("filter.Marke"));
		jLabel4.setName("jLabel4"); // NOI18N

		jTextFieldVariante.setText("");
		jTextFieldVariante.setName("jTextFieldVariante"); // NOI18N

		jComboBoxModel.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] {}));
		jComboBoxModel.setName("jComboBoxModel"); // NOI18N

		Object[] makes = makemodel.keySet().toArray();
		Arrays.sort(makes);
		jComboBoxMarke.setModel(new DefaultComboBoxModel(makes));
		jComboBoxMarke.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				makeChanged(e);
			}
		});
		jComboBoxMarke.setName("jComboBoxMarke"); // NOI18N

		jLabel5.setText(filterFormBundle.getString("filter.Model"));
		jLabel5.setName("jLabel5"); // NOI18N

		jLabel6.setText(filterFormBundle.getString("filter.Variant"));
		jLabel6.setName("jLabel6"); // NOI18N

		jLabel10.setText(filterFormBundle.getString("filter.Getriebe"));
		jLabel10.setName("jLabel10"); // NOI18N

		jComboBoxGear.setModel(new DefaultComboBoxModel(gearOptions));
		jComboBoxGear.setName("jComboBoxGear"); // NOI18N

		jComboBoxFuel.setModel(new DefaultComboBoxModel(fuelOptions));
		jComboBoxFuel.setName("jComboBoxFuel"); // NOI18N

		jLabel11.setText(filterFormBundle.getString("filter.Kraftstoff"));
		jLabel11.setName("jLabel11"); // NOI18N

		jComboBoxBody.setModel(new DefaultComboBoxModel(bodyOptions));
		jComboBoxBody.setName("jComboBoxBody"); // NOI18N

		jLabel12.setText(filterFormBundle.getString("filter.Tueren"));
		jLabel12.setName("jLabel12"); // NOI18N

		jComboBoxENorm.setModel(new DefaultComboBoxModel(eNormOptions));
		jComboBoxENorm.setName("jComboBoxENorm"); // NOI18N

		jLabel13.setText(filterFormBundle.getString("filter.E-Norm"));
		jLabel13.setName("jLabel13"); // NOI18N

		jComboBoxRadius.setModel(new DefaultComboBoxModel(radiusOptions));
		jComboBoxRadius.setName("jComboBoxRadius"); // NOI18N

		jLabel14.setText(filterFormBundle.getString("filter.Radius"));
		jLabel14.setName("jLabel14"); // NOI18N

		jLabel15.setText(filterFormBundle.getString("filter.PLZ"));
		jLabel15.setName("jLabel15"); // NOI18N

		jTextFieldPLZ.setText("");
		jTextFieldPLZ.setName("jTextFieldPLZ"); // NOI18N

		jLabel1.setText(filterFormBundle.getString("filter.Preis"));
		jLabel1.setName("jLabel1"); // NOI18N

		jComboBoxPriceFrom.setModel(new DefaultComboBoxModel(priceOptionsFrom));
		jComboBoxPriceFrom.setName("jComboBoxPriceFrom"); // NOI18N

		jComboBoxPriceTo.setModel(new DefaultComboBoxModel(priceOptionsTo));
		jComboBoxPriceTo.setName("jComboBoxPriceTo"); // NOI18N

		jSeparator1.setName("jSeparator1"); // NOI18N

		jLabel2.setText(filterFormBundle.getString("filter.Kilometer"));
		jLabel2.setName("jLabel2"); // NOI18N

		jComboBoxMileageFrom.setModel(new DefaultComboBoxModel(
				mileageOptionsFrom));
		jComboBoxMileageFrom.setName("jComboBoxMileageFrom"); // NOI18N

		jComboBoxMileageTo.setModel(new DefaultComboBoxModel(mileageOptionsTo));
		jComboBoxMileageTo.setName("jComboBoxMileageTo"); // NOI18N

		jLabel3.setText(filterFormBundle.getString("filter.Leistung"));
		jLabel3.setName("jLabel3"); // NOI18N

		jComboBoxPowerFrom.setModel(new DefaultComboBoxModel(powerOptionsFrom));
		jComboBoxPowerFrom.setName("jComboBoxPowerFrom"); // NOI18N

		jComboBoxPowerTo.setModel(new DefaultComboBoxModel(powerOptionsTo));
		jComboBoxPowerTo.setName("jComboBoxPowerTo"); // NOI18N

		jLabel7.setText(filterFormBundle.getString("filter.Baujahr"));
		jLabel7.setName("jLabel7"); // NOI18N

		jComboBoxYearFrom.setModel(new DefaultComboBoxModel(yearOptionsFrom));
		jComboBoxYearFrom.setName("jComboBoxYearFrom"); // NOI18N

		jComboBoxYearTo.setModel(new DefaultComboBoxModel(yearOptionsTo));
		jComboBoxYearTo.setName("jComboBoxYearTo"); // NOI18N

		jSeparator2.setName("jSeparator2"); // NOI18N

		jLabel8.setText(filterFormBundle.getString("filter.von"));
		jLabel8.setName("jLabel8"); // NOI18N

		jLabel9.setText(filterFormBundle.getString("filter.bis"));
		jLabel9.setName("jLabel9"); // NOI18N

		jSeparator3.setName("jSeparator3"); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(10, 10, 10)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																123,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel10)
														.addComponent(jLabel11)
														.addComponent(jLabel12)
														.addComponent(jLabel13)
														.addComponent(jLabel14)
														.addComponent(jLabel15))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jTextFieldVariante,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																191,
																Short.MAX_VALUE)
														.addComponent(
																jComboBoxGear,
																javax.swing.GroupLayout.Alignment.TRAILING,
																0, 191,
																Short.MAX_VALUE)
														.addComponent(
																jComboBoxFuel,
																javax.swing.GroupLayout.Alignment.TRAILING,
																0, 191,
																Short.MAX_VALUE)
														.addComponent(
																jComboBoxBody,
																javax.swing.GroupLayout.Alignment.TRAILING,
																0, 191,
																Short.MAX_VALUE)
														.addComponent(
																jComboBoxENorm,
																javax.swing.GroupLayout.Alignment.TRAILING,
																0, 191,
																Short.MAX_VALUE)
														.addComponent(
																jComboBoxRadius,
																javax.swing.GroupLayout.Alignment.TRAILING,
																0, 191,
																Short.MAX_VALUE)
														.addComponent(
																jTextFieldPLZ,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																191,
																Short.MAX_VALUE))
										.addContainerGap(20, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout.createSequentialGroup().addGap(
										10, 10, 10).addComponent(jLabel6)
										.addContainerGap(215, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout.createSequentialGroup().addGap(
										10, 10, 10).addComponent(jLabel5)
										.addContainerGap(215, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jSeparator2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				318,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				10,
																				10,
																				10)
																		.addComponent(
																				jSeparator1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				322,
																				Short.MAX_VALUE)))
										.addContainerGap(16, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel1)
														.addComponent(jLabel2)
														.addComponent(jLabel3)
														.addComponent(jLabel7))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.CENTER)
														.addComponent(
																jComboBoxPriceFrom,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																93,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jComboBoxMileageFrom,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																93,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jComboBoxPowerFrom,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																93,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jComboBoxYearFrom,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																93,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel8))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.CENTER)
														.addComponent(
																jComboBoxPriceTo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																93,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jComboBoxMileageTo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																93,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jComboBoxPowerTo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																93,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jComboBoxYearTo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																93,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9))
										.addContainerGap())
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout.createSequentialGroup()
										.addContainerGap(137, Short.MAX_VALUE)
										.addComponent(jComboBoxModel, 0, 191,
												Short.MAX_VALUE).addGap(20, 20,
												20))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout.createSequentialGroup()
										.addContainerGap(137, Short.MAX_VALUE)
										.addComponent(jComboBoxMarke, 0, 191,
												Short.MAX_VALUE).addGap(20, 20,
												20))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jSeparator3,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												328, Short.MAX_VALUE)
										.addContainerGap()));

		jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { jComboBoxMileageFrom,
						jComboBoxMileageTo, jComboBoxPowerFrom,
						jComboBoxPowerTo, jComboBoxPriceFrom, jComboBoxPriceTo,
						jComboBoxYearFrom, jComboBoxYearTo, jLabel8, jLabel9 });

		jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { jComboBoxBody, jComboBoxENorm,
						jComboBoxFuel, jComboBoxGear, jComboBoxMarke,
						jComboBoxModel, jComboBoxRadius, jTextFieldPLZ,
						jTextFieldVariante });

		jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { jLabel1, jLabel10, jLabel11,
						jLabel12, jLabel13, jLabel14, jLabel15, jLabel2,
						jLabel3, jLabel4, jLabel5, jLabel6, jLabel7 });

		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBoxMarke,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBoxModel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextFieldVariante,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(jLabel9))
										.addGap(9, 9, 9)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jComboBoxPriceTo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jComboBoxPriceFrom,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel1)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jComboBoxMileageTo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jComboBoxMileageFrom,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel2)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jComboBoxPowerTo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jComboBoxPowerFrom,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel3)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jComboBoxYearTo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jComboBoxYearFrom,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel7)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBoxGear,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel10))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBoxFuel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel11))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBoxBody,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel12))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBoxENorm,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel13))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBoxRadius,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel14))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextFieldPLZ,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel15))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				okButtonAction();
			}
		});
		jButton1.setText(filterFormBundle.getString("button.Speichern"));
		jButton1.setName("jButton1"); // NOI18N

		jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				cancelButtonAction();
			}
		});
		jButton2.setText(filterFormBundle.getString("button.Abbrechen"));
		jButton2.setName("jButton2"); // NOI18N

		jPanel2
				.setBorder(javax.swing.BorderFactory
						.createTitledBorder(filterFormBundle
								.getString("filter.Safety")));
		jPanel2.setName("jPanel2"); // NOI18N

		jCheckBoxABS.setText(filterFormBundle.getString("filter.ABS"));
		jCheckBoxABS.setName("jCheckBoxABS"); // NOI18N

		jCheckBoxAirbag.setText(filterFormBundle.getString("filter.Airbag"));
		jCheckBoxAirbag.setName("jCheckBoxAirbag"); // NOI18N

		jCheckBoxAllrad.setText(filterFormBundle.getString("filter.Allrad"));
		jCheckBoxAllrad.setName("jCheckBoxAllrad"); // NOI18N

		jCheckBoxESP.setText(filterFormBundle.getString("filter.ESP"));
		jCheckBoxESP.setName("jCheckBoxESP"); // NOI18N

		jCheckBoxAlarm
				.setText(filterFormBundle.getString("filter.Alarmanlage"));
		jCheckBoxAlarm.setName("jCheckBoxAllarm"); // NOI18N

		jCheckBoxWFSperre.setText(filterFormBundle
				.getString("filter.Wegfahrsperre"));
		jCheckBoxWFSperre.setName("jCheckBoxWFSperre"); // NOI18N

		jCheckBoxLock.setText(filterFormBundle
				.getString("filter.Zentralverriegelung"));
		jCheckBoxLock.setName("jCheckBoxLock"); // NOI18N

		jCheckBoxSAirbag.setText(filterFormBundle
				.getString("filter.Seitenairbags"));
		jCheckBoxSAirbag.setName("jCheckBoxSAirbag"); // NOI18N

		jCheckBoxNebel.setText(filterFormBundle
				.getString("filter.Nebelscheinwerfer"));
		jCheckBoxNebel.setName("jCheckBoxNebel"); // NOI18N

		jCheckBoxServo.setText(filterFormBundle
				.getString("filter.Servolenkung"));
		jCheckBoxServo.setName("jCheckBoxServo"); // NOI18N

		jCheckBoxTraktion.setText(filterFormBundle
				.getString("filter.Traktionskontrolle"));
		jCheckBoxTraktion.setName("jCheckBoxTraktion"); // NOI18N

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jCheckBoxTraktion,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																166,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jCheckBoxNebel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																166,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jCheckBoxLock,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																166,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jCheckBoxAlarm,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																166,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jCheckBoxAllrad,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																166,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jCheckBoxABS,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																166,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.CENTER)
														.addComponent(
																jCheckBoxServo,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																161,
																Short.MAX_VALUE)
														.addComponent(
																jCheckBoxSAirbag,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																161,
																Short.MAX_VALUE)
														.addComponent(
																jCheckBoxWFSperre,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																161,
																Short.MAX_VALUE)
														.addComponent(
																jCheckBoxESP,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																161,
																Short.MAX_VALUE)
														.addComponent(
																jCheckBoxAirbag,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																161,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxABS)
														.addComponent(
																jCheckBoxAirbag))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxAllrad)
														.addComponent(
																jCheckBoxESP))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxAlarm)
														.addComponent(
																jCheckBoxWFSperre))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxLock)
														.addComponent(
																jCheckBoxSAirbag))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxNebel)
														.addComponent(
																jCheckBoxServo))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jCheckBoxTraktion)
										.addContainerGap(12, Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory
				.createTitledBorder(filterFormBundle
						.getString("filter.Equipment")));
		jPanel3.setName("jPanel3"); // NOI18N

		jCheckBoxAlufelgen.setText(filterFormBundle
				.getString("filter.Alufelgen"));
		jCheckBoxAlufelgen.setName("jCheckBoxFelge"); // NOI18N

		jCheckBoxAKupplung.setText(filterFormBundle
				.getString("filter.Anhaengerkupplung"));
		jCheckBoxAKupplung.setName("jCheckBoxAKupplung"); // NOI18N

		jCheckBoxBordcomputer.setText(filterFormBundle
				.getString("filter.Bordcomputer"));
		jCheckBoxBordcomputer.setName("jCheckBoxBord"); // NOI18N

		jCheckBoxDachtraeger.setText(filterFormBundle
				.getString("filter.Dachtraeger"));
		jCheckBoxDachtraeger.setName("jCheckBoxDachträger"); // NOI18N

		jCheckBoxEinpark.setText(filterFormBundle
				.getString("filter.Einparkhilfe"));
		jCheckBoxEinpark.setName("jCheckBoxEinpark"); // NOI18N

		jCheckBoxESitze.setText(filterFormBundle.getString("filter.ElSitze"));
		jCheckBoxESitze.setName("jCheckBoxElSitze"); // NOI18N

		jCheckBoxFensterheber.setText(filterFormBundle
				.getString("filter.Fensterheber"));
		jCheckBoxFensterheber.setName("jCheckBoxFensterheber"); // NOI18N

		jCheckBoxKlima.setText(filterFormBundle.getString("filter.Klima"));
		jCheckBoxKlima.setName("jCheckBoxKlima"); // NOI18N

		jCheckBoxLeder.setText(filterFormBundle.getString("filter.Leder"));
		jCheckBoxLeder.setName("jCheckBoxLeder"); // NOI18N

		jCheckBoxNavi.setText(filterFormBundle.getString("filter.Navi"));
		jCheckBoxNavi.setName("jCheckBoxNavi"); // NOI18N

		jCheckBoxRadioCD.setText(filterFormBundle.getString("filter.Radio/CD"));
		jCheckBoxRadioCD.setName("jCheckBoxRadioCD"); // NOI18N

		jCheckBoxSchiebedach.setText(filterFormBundle
				.getString("filter.Schiebedach"));
		jCheckBoxSchiebedach.setName("jCheckBoxSchiebedach"); // NOI18N

		jCheckBoxStandheizung.setText(filterFormBundle
				.getString("filter.Standheizung"));
		jCheckBoxStandheizung.setName("jCheckBoxStandheizung"); // NOI18N

		jCheckBoxSitzheizung.setText(filterFormBundle
				.getString("filter.Sitzheizung"));
		jCheckBoxSitzheizung.setName("jCheckBoxSitzheizung"); // NOI18N

		jCheckBoxTempomat
				.setText(filterFormBundle.getString("filter.Tempomat"));
		jCheckBoxTempomat.setName("jCheckBoxTempomat"); // NOI18N

		jCheckBoxTuning.setText(filterFormBundle.getString("filter.Tuning"));
		jCheckBoxTuning.setName("jCheckBoxTuning"); // NOI18N

		jCheckBoxXenon.setText(filterFormBundle.getString("filter.Xenon"));
		jCheckBoxXenon.setName("jCheckBoxXenon"); // NOI18N

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jCheckBoxAlufelgen,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				166,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jCheckBoxAKupplung,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				161,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jCheckBoxBordcomputer,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				166,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jCheckBoxDachtraeger,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				161,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jCheckBoxEinpark,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				166,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jCheckBoxESitze,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				161,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jCheckBoxFensterheber,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				166,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jCheckBoxKlima,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				161,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jCheckBoxLeder,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				166,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jCheckBoxNavi,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				161,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jCheckBoxRadioCD,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				166,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jCheckBoxSchiebedach,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				161,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jCheckBoxSitzheizung,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				166,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jCheckBoxStandheizung,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				161,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jCheckBoxTempomat,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				166,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jCheckBoxTuning,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				161,
																				Short.MAX_VALUE))
														.addComponent(
																jCheckBoxXenon,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																166,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxAlufelgen)
														.addComponent(
																jCheckBoxAKupplung))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxBordcomputer)
														.addComponent(
																jCheckBoxDachtraeger))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxEinpark)
														.addComponent(
																jCheckBoxESitze))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxFensterheber)
														.addComponent(
																jCheckBoxKlima))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxLeder)
														.addComponent(
																jCheckBoxNavi))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxRadioCD)
														.addComponent(
																jCheckBoxSchiebedach))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxSitzheizung)
														.addComponent(
																jCheckBoxStandheizung))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxTempomat)
														.addComponent(
																jCheckBoxTuning))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jCheckBoxXenon)
										.addContainerGap(36, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jPanel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jPanel3,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jPanel2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton2)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jPanel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jPanel3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton2))
										.addContainerGap()));

		pack();
		setLocationRelativeTo(getOwner());
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JCheckBox jCheckBoxABS;
	private javax.swing.JCheckBox jCheckBoxAKupplung;
	private javax.swing.JCheckBox jCheckBoxAirbag;
	private javax.swing.JCheckBox jCheckBoxAlarm;
	private javax.swing.JCheckBox jCheckBoxAllrad;
	private javax.swing.JCheckBox jCheckBoxAlufelgen;
	private javax.swing.JCheckBox jCheckBoxBordcomputer;
	private javax.swing.JCheckBox jCheckBoxDachtraeger;
	private javax.swing.JCheckBox jCheckBoxESP;
	private javax.swing.JCheckBox jCheckBoxESitze;
	private javax.swing.JCheckBox jCheckBoxEinpark;
	private javax.swing.JCheckBox jCheckBoxFensterheber;
	private javax.swing.JCheckBox jCheckBoxKlima;
	private javax.swing.JCheckBox jCheckBoxLeder;
	private javax.swing.JCheckBox jCheckBoxLock;
	private javax.swing.JCheckBox jCheckBoxNavi;
	private javax.swing.JCheckBox jCheckBoxNebel;
	private javax.swing.JCheckBox jCheckBoxRadioCD;
	private javax.swing.JCheckBox jCheckBoxSAirbag;
	private javax.swing.JCheckBox jCheckBoxSchiebedach;
	private javax.swing.JCheckBox jCheckBoxServo;
	private javax.swing.JCheckBox jCheckBoxSitzheizung;
	private javax.swing.JCheckBox jCheckBoxStandheizung;
	private javax.swing.JCheckBox jCheckBoxTempomat;
	private javax.swing.JCheckBox jCheckBoxTraktion;
	private javax.swing.JCheckBox jCheckBoxTuning;
	private javax.swing.JCheckBox jCheckBoxWFSperre;
	private javax.swing.JCheckBox jCheckBoxXenon;
	private javax.swing.JComboBox jComboBoxBody;
	private javax.swing.JComboBox jComboBoxENorm;
	private javax.swing.JComboBox jComboBoxFuel;
	private javax.swing.JComboBox jComboBoxGear;
	private javax.swing.JComboBox jComboBoxMarke;
	private javax.swing.JComboBox jComboBoxMileageFrom;
	private javax.swing.JComboBox jComboBoxMileageTo;
	private javax.swing.JComboBox jComboBoxModel;
	private javax.swing.JComboBox jComboBoxPowerFrom;
	private javax.swing.JComboBox jComboBoxPowerTo;
	private javax.swing.JComboBox jComboBoxPriceFrom;
	private javax.swing.JComboBox jComboBoxPriceTo;
	private javax.swing.JComboBox jComboBoxRadius;
	private javax.swing.JComboBox jComboBoxYearFrom;
	private javax.swing.JComboBox jComboBoxYearTo;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JTextField jTextFieldPLZ;
	private javax.swing.JTextField jTextFieldVariante;
	// End of variables declaration//GEN-END:variables
	private final Filter edit;
	// jComboBox Data
	private HashMap<String, Vector<String>> makemodel;
	private Vector<String> priceOptionsFrom;
	private Vector<String> powerOptionsFrom;
	private Vector<String> mileageOptionsFrom;
	private Vector<String> yearOptionsFrom;
	private Vector<String> priceOptionsTo;
	private Vector<String> powerOptionsTo;
	private Vector<String> mileageOptionsTo;
	private Vector<String> yearOptionsTo;
	private Vector<String> fuelOptions;
	private Vector<String> gearOptions;
	private Vector<String> bodyOptions;
	private Vector<String> radiusOptions;
	private Vector<String> eNormOptions;
	private Object noMakeMsg;

	private void setData() {
		// put the data from filter
		if (edit != null) {
			// comboboxes

			if (edit.getVal("make") != null) {
				jComboBoxMarke.setSelectedItem(edit.getVal("make"));
			}
			if (edit.getVal("model") != null) {
				jComboBoxModel.setSelectedItem(edit.getVal("model"));
			}
			if (edit.getVal("priceFrom") != null) {
				jComboBoxPriceFrom.setSelectedItem(edit.getVal("priceFrom"));
			}
			if (edit.getVal("priceTo") != null) {
				jComboBoxPriceTo.setSelectedItem(edit.getVal("priceTo"));
			}
			if (edit.getVal("powerFrom") != null) {
				jComboBoxPowerFrom.setSelectedItem(edit.getVal("powerFrom"));
			}
			if (edit.getVal("powerTo") != null) {
				jComboBoxPowerTo.setSelectedItem(edit.getVal("powerTo"));
			}
			if (edit.getVal("mileageFrom") != null) {
				jComboBoxMileageFrom
						.setSelectedItem(edit.getVal("mileageFrom"));
			}
			if (edit.getVal("mileageTo") != null) {
				jComboBoxMileageTo.setSelectedItem(edit.getVal("mileageTo"));
			}
			if (edit.getVal("yearFrom") != null) {
				jComboBoxYearFrom.setSelectedItem(edit.getVal("yearFrom"));
			}
			if (edit.getVal("yearTo") != null) {
				jComboBoxYearTo.setSelectedItem(edit.getVal("yearTo"));
			}
			if (edit.getVal("body") != null) {
				jComboBoxBody.setSelectedItem(edit.getVal("body"));
			}
			if (edit.getVal("fuel") != null) {
				jComboBoxFuel.setSelectedItem(edit.getVal("fuel"));
			}
			if (edit.getVal("gear") != null) {
				jComboBoxGear.setSelectedItem(edit.getVal("gear"));
			}
			if (edit.getVal("enorm") != null) {
				jComboBoxENorm.setSelectedItem(edit.getVal("enorm"));
			}
			if (edit.getVal("radius") != null) {
				jComboBoxRadius.setSelectedItem(edit.getVal("radius"));
			}
			if (edit.getVal("variant") != null) {
				jTextFieldVariante.setText(edit.getVal("variant"));
			}
			if (edit.getVal("zip") != null) {
				jTextFieldPLZ.setText(edit.getVal("zip"));
			}

			// checkboxes
			jCheckBoxABS.setSelected(Boolean.valueOf(edit.getVal("abs")));
			jCheckBoxAirbag.setSelected(Boolean.valueOf(edit.getVal("airbag")));
			jCheckBoxSAirbag.setSelected(Boolean.valueOf(edit
					.getVal("seitenairbag")));
			jCheckBoxKlima.setSelected(Boolean.valueOf(edit.getVal("klima")));
			jCheckBoxNavi.setSelected(Boolean.valueOf(edit.getVal("navi")));
			jCheckBoxServo.setSelected(Boolean.valueOf(edit.getVal("servo")));
			jCheckBoxAllrad.setSelected(Boolean.valueOf(edit.getVal("allrad")));
			jCheckBoxEinpark.setSelected(Boolean
					.valueOf(edit.getVal("einpark")));
			jCheckBoxSchiebedach.setSelected(Boolean.valueOf(edit
					.getVal("schiebedach")));
			jCheckBoxXenon.setSelected(Boolean.valueOf(edit.getVal("xenon")));
			jCheckBoxAlufelgen.setSelected(Boolean.valueOf(edit
					.getVal("alufelgen")));
			jCheckBoxFensterheber.setSelected(Boolean.valueOf(edit
					.getVal("fensterheber")));
			jCheckBoxLeder.setSelected(Boolean.valueOf(edit.getVal("leder")));
			jCheckBoxLock.setSelected(Boolean.valueOf(edit.getVal("lock")));
			jCheckBoxESP.setSelected(Boolean.valueOf(edit.getVal("esp")));
			jCheckBoxAlarm.setSelected(Boolean.valueOf(edit.getVal("alarm")));
			jCheckBoxBordcomputer.setSelected(Boolean.valueOf(edit
					.getVal("bordcomputer")));
			jCheckBoxESitze.setSelected(Boolean.valueOf(edit.getVal("esitze")));
			jCheckBoxRadioCD.setSelected(Boolean
					.valueOf(edit.getVal("radiocd")));
			jCheckBoxTempomat.setSelected(Boolean.valueOf(edit
					.getVal("tempomat")));
			jCheckBoxWFSperre.setSelected(Boolean.valueOf(edit
					.getVal("wfsperre")));
			jCheckBoxAKupplung.setSelected(Boolean.valueOf(edit
					.getVal("akupplung")));
			jCheckBoxDachtraeger.setSelected(Boolean.valueOf(edit
					.getVal("dachtraeger")));
			jCheckBoxNebel.setSelected(Boolean.valueOf(edit.getVal("nebel")));
			jCheckBoxSitzheizung.setSelected(Boolean.valueOf(edit
					.getVal("sitzheizung")));
			jCheckBoxStandheizung.setSelected(Boolean.valueOf(edit
					.getVal("standheizung")));
			jCheckBoxTraktion.setSelected(Boolean.valueOf(edit
					.getVal("traktion")));
		}
	}

	@SuppressWarnings("unchecked")
	private void initData() {
		makemodel = new HashMap<String, Vector<String>>();

		SAXBuilder builder = new SAXBuilder(false);

		try {
			Document inXML = builder.build(FilterForm.class
					.getResource("gui.in.xml"));
			XPath makePath = XPath.newInstance("/gui.in/makemodeldata/make");
			XPath modelPath = XPath.newInstance("model/@key");
			List<Element> makeList = makePath.selectNodes(inXML);
			for (Element make : makeList) {
				Vector<String> tmpV = new Vector<String>();
				List<Attribute> modelList = modelPath.selectNodes(make);
				for (Attribute model : modelList) {
					tmpV.add(model.getValue());
				}
				Collections.sort(tmpV);
				makemodel.put(make.getAttributeValue("key"), tmpV);
			}

			// Price
			priceOptionsFrom = getOptions(inXML,
					"/gui.in/options/priceFrom/option/@key");
			priceOptionsTo = getOptions(inXML,
					"/gui.in/options/priceTo/option/@key");
			// Power
			powerOptionsFrom = getOptions(inXML,
					"/gui.in/options/powerFrom/option/@key");
			powerOptionsTo = getOptions(inXML,
					"/gui.in/options/powerTo/option/@key");
			// Mileage
			mileageOptionsFrom = getOptions(inXML,
					"/gui.in/options/mileageFrom/option/@key");
			mileageOptionsTo = getOptions(inXML,
					"/gui.in/options/mileageTo/option/@key");
			// Year
			yearOptionsFrom = getOptions(inXML,
					"/gui.in/options/yearFrom/option/@key");
			yearOptionsTo = getOptions(inXML,
					"/gui.in/options/yearTo/option/@key");
			// Gear
			gearOptions = getOptions(inXML, "/gui.in/options/gear/option/@key");
			// Fuel
			fuelOptions = getOptions(inXML, "/gui.in/options/fuel/option/@key");
			// Body
			bodyOptions = getOptions(inXML, "/gui.in/options/body/option/@key");
			// E-Norm
			eNormOptions = getOptions(inXML,
					"/gui.in/options/enorm/option/@key");
			// Radius
			radiusOptions = getOptions(inXML,
					"/gui.in/options/radius/option/@key");

		} catch (JDOMException e) {
			e.printStackTrace();
			MessageHandler.getHandler().broadcast(
					"Can not initiate filter form", MessageType.ERROR);
		} catch (IOException e) {
			e.printStackTrace();
			MessageHandler.getHandler().broadcast(
					"Can not initiate filter form", MessageType.ERROR);
		}
	}

	/**
	 * Get options from gui input file.
	 * 
	 * @param source
	 *            XML Document
	 * @param path
	 *            a path to attributes (not elements!)
	 * @return
	 */
	@SuppressWarnings("unchecked")
	private Vector<String> getOptions(Document source, String path) {
		Vector<String> tmpOptions = new Vector<String>();
		try {
			XPath optPath = XPath.newInstance(path);
			List<Attribute> optList = optPath.selectNodes(source);
			for (Attribute option : optList) {
				tmpOptions.add(option.getValue());
			}
		} catch (JDOMException e) {
			e.printStackTrace();
		}
		return tmpOptions;
	}

	@Action
	public void okButtonAction() {
		if (((String) jComboBoxMarke.getSelectedItem()).equals("")) {
			JOptionPane.showMessageDialog(null, this.noMakeMsg, "Fehler",
					JOptionPane.ERROR_MESSAGE);
			return;
		}

		Filter f;
		if (edit == null) {
			f = new Filter();
		} else {
			f = edit;
		}

		// Collect data from the form
		f.setVal("make", (String) jComboBoxMarke.getSelectedItem());
		f.setVal("model", (String) jComboBoxModel.getSelectedItem());
		f.setVal("variant", jTextFieldVariante.getText());

		// From-To Values
		f.setVal("priceFrom", (String) jComboBoxPriceFrom.getSelectedItem());
		f.setVal("priceTo", (String) jComboBoxPriceTo.getSelectedItem());
		f.setVal("mileageFrom", jComboBoxMileageFrom.getSelectedItem()
				.toString());
		f.setVal("mileageTo", jComboBoxMileageTo.getSelectedItem().toString());
		f.setVal("powerFrom", jComboBoxPowerFrom.getSelectedItem().toString());
		f.setVal("powerTo", (String) jComboBoxPowerTo.getSelectedItem());
		f.setVal("yearFrom", jComboBoxYearFrom.getSelectedItem().toString());
		f.setVal("yearTo", (String) jComboBoxYearTo.getSelectedItem());

		f.setVal("gear", (String) jComboBoxGear.getSelectedItem());
		f.setVal("fuel", (String) jComboBoxFuel.getSelectedItem());
		f.setVal("body", (String) jComboBoxBody.getSelectedItem());
		f.setVal("enorm", (String) jComboBoxENorm.getSelectedItem());

		f.setVal("zip", jTextFieldPLZ.getText());
		f.setVal("radius", (String) jComboBoxRadius.getSelectedItem());

		// Checkboxes
		f.setVal("abs", b2s(jCheckBoxABS.isSelected()));
		f.setVal("airbag", b2s(jCheckBoxAirbag.isSelected()));
		f.setVal("seitenairbag", b2s(jCheckBoxSAirbag.isSelected()));
		f.setVal("klima", b2s(jCheckBoxKlima.isSelected()));
		f.setVal("navi", b2s(jCheckBoxNavi.isSelected()));
		f.setVal("servo", b2s(jCheckBoxServo.isSelected()));
		f.setVal("allrad", b2s(jCheckBoxAllrad.isSelected()));
		f.setVal("einpark", b2s(jCheckBoxEinpark.isSelected()));
		f.setVal("schiebedach", b2s(jCheckBoxSchiebedach.isSelected()));
		f.setVal("xenon", b2s(jCheckBoxXenon.isSelected()));
		f.setVal("alufelgen", b2s(jCheckBoxAlufelgen.isSelected()));
		f.setVal("fensterheber", b2s(jCheckBoxFensterheber.isSelected()));
		f.setVal("leder", b2s(jCheckBoxLeder.isSelected()));
		f.setVal("lock", b2s(jCheckBoxLock.isSelected()));
		f.setVal("esp", b2s(jCheckBoxESP.isSelected()));
		f.setVal("alarm", b2s(jCheckBoxAlarm.isSelected()));
		f.setVal("bordcomputer", b2s(jCheckBoxBordcomputer.isSelected()));
		f.setVal("esitze", b2s(jCheckBoxESitze.isSelected()));
		f.setVal("radiocd", b2s(jCheckBoxRadioCD.isSelected()));
		f.setVal("tempomat", b2s(jCheckBoxTempomat.isSelected()));
		f.setVal("wfsperre", b2s(jCheckBoxWFSperre.isSelected()));
		f.setVal("akupplung", b2s(jCheckBoxAKupplung.isSelected()));
		f.setVal("dachtraeger", b2s(jCheckBoxDachtraeger.isSelected()));
		f.setVal("nebel", b2s(jCheckBoxNebel.isSelected()));
		f.setVal("sitzheizung", b2s(jCheckBoxSitzheizung.isSelected()));
		f.setVal("standheizung", b2s(jCheckBoxStandheizung.isSelected()));
		f.setVal("traktion", b2s(jCheckBoxTraktion.isSelected()));

		// Send
		MessageHandler.getHandler().receiveMessage(
				new MessageCollector(f, MessageType.ADD));

		// Close form
		this.dispose();
	}

	private String b2s(boolean b) {
		if (b) {
			return "true";
		} else {
			return ""; // Default value
		}
	}

	@Action
	public void cancelButtonAction() {
		if (edit != null) {
			MessageHandler.getHandler().receiveMessage(
					new MessageCollector(edit, MessageType.ADD));
		}
		this.dispose();
	}

	private void makeChanged(ActionEvent e) {
		JComboBox cb = (JComboBox) e.getSource();
		String makeName = (String) cb.getSelectedItem();
		jComboBoxModel.setModel(new DefaultComboBoxModel(makemodel
				.get(makeName)));
	}
}
